import { Metadata } from 'next';
import ProjectEstimator from '@/components/ai/ProjectEstimator';
import { ShieldCheck, Zap, Code2, Sparkles } from 'lucide-react';

export const metadata: Metadata = {
  title: 'AI Project Scope & Cost Estimator — CoderNest Digital Solutions',
  description:
    'Calculate your project scope, recommended Next.js technology stack, and estimated budget in under 60 seconds with our AI Architecture Estimator.',
  openGraph: {
    title: 'AI Project Scope & Cost Estimator — CoderNest',
    description:
      'Instant architectural scope, timeline breakdown, and budget calculator for Next.js, SaaS, and full-stack software platforms.',
    url: 'https://codernest.agency/estimator',
  },
};

export default function EstimatorPage() {
  return (
    <div className="relative min-h-screen py-16 sm:py-24 px-4 sm:px-6 lg:px-8 overflow-hidden bg-slate-50 dark:bg-slate-950">
      {/* Ambient background glows */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-blue-500/10 dark:bg-blue-600/10 blur-[130px] rounded-full pointer-events-none" />
      <div className="absolute bottom-1/4 right-10 w-[400px] h-[400px] bg-indigo-500/10 dark:bg-indigo-600/10 blur-[110px] rounded-full pointer-events-none" />

      <div className="relative max-w-5xl mx-auto space-y-12">
        {/* Top Trust Proof */}
        <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-slate-500 dark:text-slate-400">
          <span className="flex items-center gap-1.5 font-medium">
            <Zap className="w-4 h-4 text-amber-500" /> Sub-60s Architecture Sizing
          </span>
          <span className="flex items-center gap-1.5 font-medium">
            <Code2 className="w-4 h-4 text-blue-500" /> Enterprise Next.js App Router
          </span>
          <span className="flex items-center gap-1.5 font-medium">
            <ShieldCheck className="w-4 h-4 text-emerald-500" /> Benchmarked against Flagship Systems
          </span>
        </div>

        {/* The Interactive Estimator Lead Magnet Component */}
        <ProjectEstimator />

        {/* Bottom Callout */}
        <div className="text-center pt-8 border-t border-slate-200 dark:border-white/10 max-w-2xl mx-auto">
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
            All estimates generated by our AI Architecture Engine reflect realistic engineering velocity, strict TypeScript standards, automated CI/CD pipelines, and high-concurrency cloud deployments.
          </p>
        </div>
      </div>
    </div>
  );
}
